# Generated by Django 4.1.7 on 2023-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_image_alter_measurement_id_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
